# Generated by Django 5.0.3 on 2024-03-16 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0003_alter_workshops_codigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workshops',
            name='fecha_wp',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
