# Generated by Django 5.0.3 on 2024-03-18 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0004_alter_workshops_fecha_wp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workshops',
            name='codigo',
            field=models.CharField(blank=True, max_length=200, unique=True),
        ),
    ]
